version: "3.9"
services:
  postgres:
    image: postgres:14.0
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_DB: "tests"
      POSTGRES_USER: "gree"
      POSTGRES_PASSWORD: "8771"
    ports:
      - "5432:5432"
    volumes:
       - postgres_data:/home/postgres
volumes:
  postgres_data:
