apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *" # запускать раз в минуту
  concurrencyPolicy: Allow # Конкурентный запуск Job-в

  jobTemplate:

    spec:

      backoffLimit: 2
      activeDeadlineSeconds: 100

      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never