apiVersion: v1
kind: Secret
metadata:
  name: coolap-secret
  namespace: coolapp
type: Opaque
stringData:
  fernet_key: "some-secret-pass123"
data: # base64 encoded
  username: YWRtaW4=
  password: Qjd3SXRZbEhlUlIx
