apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: service-a-gw
spec:
  selector:
    istio: ingressgateway # говорит Istio, что этот Gateway применяется только к подам, у которых есть такая метка
  servers:
    - port:
        number: 80 # Порт, выставленный service-м наружу
        name: http
        protocol: HTTP
      hosts:
        - "*"